version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A eMenu worker --loglevel=Info &
    depends_on:
      - redis
    environment:
      - POSTGRES_NAME=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  celery-beat:
    build: .
    command: celery -A eMenu beat --loglevel=Info &
    depends_on:
      - redis
    environment:
      - POSTGRES_NAME=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
  web:
    build: .
      #command: bash web_startup.sh
    command: python manage.py runserver 0.0.0.0:8000
      #command: python manage.py test
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    depends_on:
      - db
      - celery
      - celery-beat


