# Generated by Django 3.2.12 on 2022-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
