# Generated by Django 3.2.12 on 2022-02-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0002_alter_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='menus', to='menuapi.Meal'),
        ),
    ]
