# Generated by Django 3.2.12 on 2022-02-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0004_auto_20220218_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meal_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
