# Generated by Django 3.2.12 on 2022-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0005_menu_meal_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='meal_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
