# Generated by Django 3.2.12 on 2022-02-21 17:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0006_alter_menu_meal_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='prep_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
